import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { describe, it, expect } from "vitest";
import { buildGraphSvg, escapeXml, type SvgExportInput } from "../../src/webview/graph/svgExport";
import { canvasSize } from "../../src/webview/graph/metrics";
import type { AppState } from "../../src/protocol/messages";

// Reuses harness/state.json (checked in, regenerated by `node scripts/dump-state.mjs` from the
// REAL broken-project fixture via the real MigrationService — see the harness's own header
// comment) so this suite exercises buildGraphSvg against the exact same AppState the F5/Playwright
// checks do, rather than a hand-rolled layout that could drift from what the pipeline actually
// produces. 13 layout.nodes (12 revisions + 1 ghost for `deadbeef0000`), 12 edges (1 broken), 3
// heads, 1 broken revision, 1 merge revision, 0 current (dbReachable false in this fixture).
const here = path.dirname(fileURLToPath(import.meta.url));
const STATE_PATH = path.join(here, "../../harness/state.json");
const state = JSON.parse(readFileSync(STATE_PATH, "utf8")) as AppState;

function baseInput(overrides: Partial<SvgExportInput> = {}): SvgExportInput {
  return {
    layout: state.layout,
    laneColors: state.laneColors,
    ui: state.ui,
    counts: state.counts,
    projectLabel: state.project!.label,
    ...overrides,
  };
}

/** Counts of the `<g `/`<path `/`<svg ` open tags this test suite relies on — all of this file's
 * generated markup uses exactly one `<g data-node-id="...">` per layout node and nothing else
 * opens a `<g>`, so a raw substring count doubles as a structural sanity check (see the brief's
 * "13 <g card groups" / "12 <path" assertions). */
function countTag(svg: string, tag: string): number {
  return (svg.match(new RegExp(`<${tag}[ />]`, "g")) ?? []).length;
}

describe("svgExport — buildGraphSvg structure (real broken-fixture state)", () => {
  const svg = buildGraphSvg(baseInput());

  it("root <svg> has the correct width/height for comfortable + newest-bottom", () => {
    const expected = canvasSize(state.layout, state.ui, state.ui.density);
    expect(state.ui.order).toBe("newest-bottom");
    expect(state.ui.density).toBe("comfortable");
    expect(svg.startsWith(`<svg xmlns="http://www.w3.org/2000/svg" width="${expected.w}" height="${expected.h}" viewBox="0 0 ${expected.w} ${expected.h}">`)).toBe(true);
  });

  it("one <g> card group per layout node (12 revisions + 1 ghost = 13)", () => {
    expect(state.layout.nodes.length).toBe(13);
    expect(countTag(svg, "g")).toBe(13);
  });

  it("one <path> per edge (12)", () => {
    expect(state.layout.edges.length).toBe(12);
    expect(countTag(svg, "path")).toBe(12);
  });

  it("exactly one dashed-red path (the broken ghost edge)", () => {
    const dashedRed = svg.match(/<path[^>]*stroke="#f14c4c"[^>]*stroke-dasharray="5 4"/g) ?? [];
    expect(dashedRed.length).toBe(1);
  });

  it("badge texts HEAD/MERGE/BROKEN are present (this fixture has no CURRENT node)", () => {
    expect(svg).toContain(">HEAD<");
    expect(svg).toContain(">MERGE<");
    expect(svg).toContain(">BROKEN<");
    expect(svg).not.toContain(">CURRENT<");
  });

  it("the ghost node's dashed-red card is present", () => {
    expect(svg).toContain('data-node-id="deadbeef0000"');
    expect(svg).toContain("missing revision");
  });
});

describe("svgExport — XML escaping", () => {
  it("escapeXml escapes all five predefined entities, & first", () => {
    expect(escapeXml(`<script>&"'`)).toBe("&lt;script&gt;&amp;&quot;&apos;");
  });

  it("a revision message containing markup/quotes is entity-escaped in the output, never raw", () => {
    const dangerousMessage = `<script>&"'`;
    const layout = {
      ...state.layout,
      nodes: state.layout.nodes.map((n) => (n.id === "8f2a1c9d4e07" ? { ...n, message: dangerousMessage } : n)),
    };
    const svg = buildGraphSvg(baseInput({ layout }));

    expect(svg).not.toContain(dangerousMessage);
    expect(svg).toContain(escapeXml(dangerousMessage));
    // Balanced-ish sanity check per the brief: no stray unescaped `&` outside a named entity.
    expect(svg.match(/&(?!amp;|lt;|gt;|quot;|apos;)/g)).toBeNull();
  });

  it("a project label containing markup is entity-escaped in the title block", () => {
    const svg = buildGraphSvg(baseInput({ projectLabel: `weird & <broken> "project"` }));
    expect(svg).not.toContain(`weird & <broken> "project"`);
    expect(svg).toContain(escapeXml(`weird & <broken> "project"`));
  });
});

describe("svgExport — message truncation", () => {
  it("a message longer than fits CARD_W is hard-truncated with a trailing ellipsis", () => {
    const longMessage = "x".repeat(80);
    const layout = {
      ...state.layout,
      nodes: state.layout.nodes.map((n) => (n.id === "8f2a1c9d4e07" ? { ...n, message: longMessage } : n)),
    };
    const svg = buildGraphSvg(baseInput({ layout }));

    expect(svg).not.toContain(longMessage);
    expect(svg).toContain("…");
    // The truncated run of x's should be shorter than the original message.
    const match = svg.match(/(x+)…/);
    expect(match).not.toBeNull();
    expect(match![1].length).toBeLessThan(longMessage.length);
  });

  it("a short message is left untouched (no ellipsis)", () => {
    const svg = buildGraphSvg(baseInput());
    // "create products table" (8f2a1c9d4e07's real message) comfortably fits CARD_W.
    expect(svg).toContain("create products table<");
  });
});

describe("svgExport — order flip", () => {
  it("a fixed node's card y position swaps relative order between newest-top and newest-bottom", () => {
    // 5c0d13aa7d9f is row 0 (newest); 8f2a1c9d4e07 is the last row (oldest) in this fixture.
    const newestId = "5c0d13aa7d9f";
    const oldestId = "8f2a1c9d4e07";

    const svgTop = buildGraphSvg(baseInput({ ui: { ...state.ui, order: "newest-top" } }));
    const svgBottom = buildGraphSvg(baseInput({ ui: { ...state.ui, order: "newest-bottom" } }));

    const yTopNewest = extractCardY(svgTop, newestId);
    const yTopOldest = extractCardY(svgTop, oldestId);
    const yBottomNewest = extractCardY(svgBottom, newestId);
    const yBottomOldest = extractCardY(svgBottom, oldestId);

    // newest-top: newest row sits above (smaller y than) the oldest row.
    expect(yTopNewest).toBeLessThan(yTopOldest);
    // newest-bottom: the relationship flips — newest now sits below (larger y than) oldest.
    expect(yBottomNewest).toBeGreaterThan(yBottomOldest);
  });
});

/** Pulls the y coordinate of the first `<rect>` inside `<g data-node-id="id">...</g>` — the
 * card's background rect, always the first shape emitted (see buildRevisionCard). */
function extractCardY(svg: string, id: string): number {
  const groupStart = svg.indexOf(`data-node-id="${id}"`);
  expect(groupStart).toBeGreaterThanOrEqual(0);
  const rectMatch = /<rect x="[^"]*" y="([^"]*)"/.exec(svg.slice(groupStart));
  expect(rectMatch).not.toBeNull();
  return Number(rectMatch![1]);
}
